# Generated by Django 4.1.3 on 2022-12-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydata',
            old_name='county',
            new_name='country',
        ),
    ]
